api_keys:
  google_api_key: "AIzaSyAGq8UhaBqAcESLtZMSOVJgnTQ0Qyj_-RI"
  cloudflare_account_id: "7d49ef94c4f3ac063f41738c36502171"
  cloudflare_api_token: "VSQF-uAre3KgN8DXksORyVXWEWhVfx6Qx_TjeIbC"

rss_feeds:
  hf_papers: "http://localhost/huggingface_daily_papers.atom"
  pwc_papers: "http://localhost/pwc_daily_papers.atom"
  git_repos: "http://localhost/github_repos.atom"
  artificial_intelligence_reddit: "http://localhost/ArtificialInteligence_top_posts.atom"
  machine_learning_reddit: "http://localhost/MachineLearning_top_posts.atom"
  machine_learning_news_reddit: "http://localhost/machinelearningnews_top_posts.atom"
  technology_reddit: "http://localhost/technology_top_posts.atom"

models:  
  audio_model:
    name: "gemini-2.5-flash-preview-tts"
    multi_speaker_voice_config:
      speakers:
        Alex:
          voice_name: "Sadaltager"
        Ben:
          voice_name: "Sulafat"
  image_model:
    name: "@cf/black-forest-labs/flux-1-schnell"

output_paths:
  images: "img"
  podcasts: "podcasts"
  newsletters: "newsletters"